import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";

import SideBar from "@/app/ui/home/SideBar/SideBar";
import TopBar from "@/app/ui/home/TopBar/TopBar";

import "@/style/globals.scss";
import styles from "./layout.module.scss";

import type { Metadata } from "next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Next Gallery",
    default: "Next Gallery",
  },
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <div className={styles.root}>
            <div className={styles.topBarContainer}>
              <TopBar />
            </div>
            <div className={styles.contentContainer}>
              <div className={styles.sideBarContainer}>
                <SideBar />
              </div>
              <div className={styles.pageContainer}>{children}</div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
